name: Run tests

on:
  push:
    branches-ignore:
      - main

env:
  PNPM_VERSION: "9.0.4"
  NODE_VERSION: "18.20.5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test

      # TODO add coverage using
      # <https://github.com/marketplace/actions/code-coverage-summary>
      # once nyc works again
  check-build-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm run -r build
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: "${{ env.PNPM_VERSION }}"
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate docs for all packages
        run: pnpm run -r typedoc
